---
title: "Analisi del Ricavo Full Time Equivalente per Dipartimento"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
tabIZSLER <- readRDS(file = here("data", "processed",   "TabellaGenerale.rds"))
FTEPD <- readRDS(file = here("data", "processed",   "FTEPD.rds"))
dtmensili <- tabIZSLER %>% 
  rename( "Prestazioni" = TotPrestazioni, "Valorizzazione" = TotTariff, "VP" = TotFattVP, "AI" = TAI, 
          "COSTI" = TotCost,   Anno = ANNO) %>%   
  group_by(Dipartimento,Anno, MESE ) %>% 
  summarise_at(c("Prestazioni", "Valorizzazione",  "VP", "AI", "FTED", "FTEC","COSTI"), sum, na.rm = T) %>% 
  mutate(RT = (Valorizzazione+VP+AI),
         FTET = FTED+FTEC,
         Prestazionic = cumsum(Prestazioni), 
         Valorizzazionec = cumsum(Valorizzazione), 
         VPc = cumsum(VP), 
         AIc = cumsum(AI), 
         COSTIc = cumsum(COSTI), 
         RTc = cumsum(RT)) %>%   
  filter(Prestazionic >0) %>% 
  filter(Anno >=2021) %>% 
  left_join(FTEPD ,  by=c("Dipartimento",  "Anno" = "anno")) %>%  
  mutate(RFTE = RT/(FTET*(FTp/100)), 
         low= RFTE- 0.10*RFTE, 
         high = RFTE + 0.10*RFTE, 
         delta = high-low, 
         fakep = RFTE+rnorm(12, 0, 0.10*RFTE), 
         fteTD = 150.1*(FTp/100), 
         fteTC = 142.2*(FTp/100))
```

Di seguito è riportata l'analisi dell'andamento mensile del Ricavo Full Time Equivalente del 2021 per Dipartimento.

## Ricavi totali (RT)
Gli RT per ogni dipartimento sono calcolati a partire dai dati forniti dal datawerehouse DW_COGEP, sommando sia l'attività valorizzata a tariffario,  quella fatturata, ricavi dalla Vendita dei prodotti (VP) e dall'attività interna (AI). 

## FTE
I FTE   sono calcolati come il rapporto tra le ore complessivamente erogate dal personale di comparto e dirigenza e le ore previste per un full time equivalente sulla base del contratto (36h settimanli per il comparto e 38 per la dirigenza)

## FTE programmato
In fase di programmazione i responsabili dei Dipartimenti hanno assegnato una % dei FTE disponibili al 1/1/2021 alle attività istituzionali dette anche valorizzate. 
Questa percentuale rappresenta la quota di FTE programmato che viene utilizzata per il calcolo del RFTE


## Ricavo Full Time Equivalente (RFTE)
L'RFTE è un indicatore di performance adottato in Istituto come indicatore dell'efficienza delle attività istituzionali che tiene conto dei volumi di attività valorizzata e delle risorse a disposizione per la loro realizzazione misurate come FTE. A partire dal 2022 l'RFTE è assegnato a tutte le strutture che erogano attività analitiche come obiettivo di efficienza. Il target previsto è: raggiungimento di almeno il 90% del valore di RFTE al 31/12/2021.


## Analisi dell'andamento del RFTE e dei suoi elementi (RT e FTE) nel 2021







 
