---
title: "COGEPERF Documentazione"
author: "Tranquillo"
date: "11/2/2022"
output: html_document
---

## Presentazione generale

Questo documento costituisce materiale di supporto all'applicativo shiny _COGEPERF_. 

_COGEPERF_ è un applicativo shiny sviluppato dall' ufficio Controllo di Gestione e Performance, come strumento di reporting del sistema di performance e controllo di gestione dell'IZSLER. 
L'applicativo è costituito dalle seguenti app:

- Applicativo principale (_COGEPERF_): dashboard che riporta i principali key Performance Indicator (KPI) dell'IZSLER in formato numerico, tabellare e grafico per Dipartimento e Reparto.

- Applicativo costiricavi: collegato all'applicativo COGEPERF mediante url ma totalmente autonomo nello sviluppo del codice. Questo applicativo riporta i dati delle attività, ricavi e costi per Centro di Costo dell'IZSLER, in formato tabellare e grafico. 

Entreambi gli applicativi sono sviluppati con  pacchetto Shiny del linguaggio R. 


__COGEPERF__ e __costiricavi__ sono ospitati su un server LINUX in ambiente AZURE all'indirizzo rshiny.izsler.it, in cui è installato una versione aggiornata di SHINYSERVER attraverso la tecnologia docker

L'accesso agli applicativi è consentito solo agli utenti IZSLER loggati all'interno della rete dell'Istituto. 

Di seguito per i due applicativi vengono illustrate le fonti dati, le modalità di aggiornamento, le funzioni costruite ad hoc, i calcoli eseguiti ecc.

## _COGEPERF_

L'app è strutturata in un Rproj di RSTUDIO (IDE di R) che comprende la seguente struttura:

**descrivere le cartelle e i file**


## R
Questa cartella contiene i seguenti file:

- _PREPARAZIONE DATI.R_

- _Start.R_

- _librerie.R_

e la cartella _rcode vari_ che contiene codici di R temporanei usati per sviluppare tabelle, grafici e funzioni da inserire nelle applicazioni principali. Quando sono implementate nel codice principale possono essere cancellati.


#### PREPARAZIONE DATI.R
Questo file è estremamente importante perchè contiene i codici di preparazione e integrazione delle diverse fonti dati che sono utilizzati per la costruzione dell'app principale e secondaria.
Tramite il file Start.R che richiama tutto il file di preparazione vengono eseguiti tutte le linee di codice. Il file va utilizzato in fase di aggiornamento dei dati. L'output è rappresentato da diversi file .RDS che contengono i dati opportunamente rielaborati che saranno utilizzati dall'app shiny. I suddetti file vengono salvati nella cartella **processed** (vedi struttura project). Di seguito una dettagliata descrizione e spiegazione dove necessario dei codici presenti nel file.

##### Connessione ai database.
E' necessario connettersi a tre differenti database: 

Al database COGEDW per l'acquisizione dei dati relativi alle ore lavorate dal personale IZSLER, utile sia per il calcolo del FTE che per la collocazione del personale nelle varie strutture e per i dati dei costi e ricavi dal DW del controllo di gestione.

Al database IZSLER per i dati relativi alle accettazioni effettuate dal reparto Gestione Centralizzata delle richieste dell'Utenza

Al database Obiettivistrategici per i dati relativi alla rendicontazione degli obiettivi di performance ( solo per l'anno 2021 e 2022- dal programma berenice, che sarà sostituito per le attività del ciclo delle performance dal 2023 con nuovo applicativo)


#### Start.r
## global.r
## ui.r
## server.r



